### ISSUE TITLE
Provide the necessary command-line steps to create OAuth tokens

### ISSUE THREAD

**Issue by olberger** [photo/openphoto-python#10]
At the moment, it is very hard to find the details on how to connect via oauth IMHO.

The script openphoto should IMHO be able to prompt the user and direct him/her in what needs to be done to connect with OAuth.

It should probably do things like print "go to your browser at http:///... and click ok" in the flow of validating token requests and such.

Hope this helps.

**Comment by sneakypete81** [comment]
Implemented in PR #32.
