### ISSUE TITLE
Make the library more Pythonic

### ISSUE THREAD

**Issue by sneakypete81** [photo/openphoto-python#12]
I started using this (excellent!) Python library, and pretty quickly found myself wrapping the raw GET/POST calls up into Python objects.

So instead of:

```
resp = client.get("/photos/list.json")
resp = client.post("/photo/62/update.json", {'tags': 'tag1,tag2'})
```

I can:

```
photos = client.photos_list()
photos[0].update(tags=["tag1", "tag2"])
```

This would hopefully make the library easier to use, since it abstracts the API URL constructions and responses.

@jmathai, @walkah: what do you think? Is this useful, or beyond what we should be doing here?

**Comment by walkah** [comment]
I'm all for it! I know that @jmathai was hoping to keep the various libraries fairly consistent. Jaisen, I think this would make the client much easier to use - can we start with Python and revisit the other libraries?

**Comment by sneakypete81** [comment]
Sorry, I'm still learning the GitHub flow.. consider this a duplicate of my pull request in issue #13!

**Comment by jmathai** [comment]
@walkah @sneakypete81 No opposition from me. Whatever makes the most sense for Python devs is > than my philosophical desire to keep the libraries consistent :)

**Comment by walkah** [comment]
Cool. I'll review the pull request then when I get a chance. @jmathai maybe I'll have a look at bringing some of the other libraries in line - cake and eat it too ;-)

**Comment by jmathai** [comment]
@walkah Possible to leave them backwards compatible for a few versions?

**Comment by walkah** [comment]
I would think that's a very good idea, yes.

**Comment by sneakypete81** [comment]
Makes sense to me. Most of my changes are additions rather than modifications to existing behaviour, but you can consider whether or not to include the following modifications to the get() and set() method behaviour:
1. Parameters are passed in as keywords rather than a single dictionary: get(endpoint, param1=value1, param2=value2) instead of get(endpoint, {"param1": value1, "param2": value2}). 
2. Lists and boolean parameters are handled correctly. This doesn't affect compatibility, and seems like a good idea.
3. The HTTP response is (optionally) parsed to a dict. The old behaviour can still be requested by specifying "process_response=False". We could make this the default if you like - I chose to make the default "True" since a dict is more useful than a JSON string.
4. Error response codes (optionally) raise exceptions. As above.
