### ISSUE TITLE
Delete methods should return boolean

### ISSUE THREAD

**Issue by sneakypete81** [photo/openphoto-python#20]
The tag/album/photo delete methods really ought to return the "True/False" return value from the API call.

I'm not sure if the API would ever return False without also raising an error code (which would raise an exception), but it's worth making this consistent anyway.

**Comment by jmathai** [comment]
The delete API returns `code:204` and `result:true` when successful.

If you don't have permission to delete you'll get `code:403` and `result:null`

On an error it returns `error:500` and `result:false`.

**Comment by jmathai** [comment]
For reference .... https://github.com/photo/frontend/blob/master/src/libraries/controllers/ApiAlbumController.php#L40
