### ISSUE TITLE
Rename to Trovebox

### ISSUE THREAD

**Issue by sneakypete81** [photo/openphoto-python#22]
@walkah, @jmathai: when and how would you like to do this? I assume the Trovebox name is to be used everywhere eventually?

**Comment by jmathai** [comment]
Name change for the open source project TBD.

**Comment by sneakypete81** [comment]
Ok, I'll close this for now then, and we can revisit later if necessary.

**Comment by sneakypete81** [comment]
I'm hoping to post the first release to PyPI soon. @jmathai: this is a great opportunity to get the Trovebox/OpenPhoto naming resolved.

I realise there's quite a bit of legacy documentation, filenames etc. that would need to change, but the situation at present is quite confusing IMHO, particularly for new users:
- The openphoto/frontend code is branded as Trovebox
- I download the Trovebox mobile app to access my self-hosted OpenPhoto site
- I use the OpenPhoto python library to access my Trovebox photos
- New documentation is at trovebox.com/documentation, and applies to both OpenPhoto and Trovebox
- Documentation is at theopenphotoproject.org too, but it hasn't been updated for a while

What is the self-hosted site to be called? OpenPhoto? Trovebox Community Edition?

Should openphoto-python and friends be renamed to trovebox-xxxx?

Should the openphoto-python package itself be called openphoto or trovebox?

Should all openphoto-python documentation keep referring only to OpenPhoto, or to "OpenPhoto/Trovebox" or just "Trovebox?

I know that any transition will take time, but it would be great to know the final goal.

Thanks!

**Comment by jmathai** [comment]
@sneakypete81 The final goal is that everything is known as Trovebox.

The self hosted version will be called Trovebox {something} but for all practical purposes, libraries should be named Trovebox.

As far as renaming the repos, I'm fine with that. I don't know if they should be prefixed with the name 'trovebox' though. Just 'python' is probably fine.

theopenphotoproject.org will soon redirect to trovebox.com

**Comment by sneakypete81** [comment]
Thanks @jmathai, that seems like a very good approach.

> As far as renaming the repos, I'm fine with that. I don't know if they should be prefixed with the name 'trovebox' though. Just 'python' is probably fine.

That's ok for the main github repository (photo/python). But it would mean github forks would be named "username/python", which is not ideal.

I'll leave this name change up to you, so it can be done in conjunction with the other repositories.

**Comment by jmathai** [comment]
> That's ok for the main github repository (photo/python). But it would mean github forks would be named "username/python", which is not ideal.

You're right. Let's change it to trovebox-python. I'm fine to do this now...we just need to clean up links from trovebox.com. I don't know if Github handles repo renames better than they used to by redirecting to the new repo.
