### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by sneakypete81** [photo/openphoto-python#36]
I've had a crack at this, with the aim of supporting both Python 2 and 3 from the same codebase. This involved:
- Running 2to3.py
- oauth2 doesn't support Python 3, so replaced with requets-oauthlib (this also cleans up a bit of multipart post magic)
- Cleaning up (using PyLint)

As a result of the above, we can support Python 2.6, 2.7 and 3.3. Maintaining support for 2.5 at the same time as 3.x is difficult (and messy).

To avoid conflicts, I'd like to wait until the last few PRs are merged before doing any more.

Any comments?

**Comment by jmathai** [comment]
Deferring to @walkah on this one for comments.

**Comment by sneakypete81** [comment]
@walkah: any comments? In particular:
- The update of httplib/oauth2 to requests-oauthlib - any problem with this?
- Limiting supported Python versions to 2.6+ (the latest version that supports the majority of Python 3 updates)

I think Python 3 support is more valuable than any potential problems with the above, but would value your opinion before merging this.
