### ISSUE TITLE
use setuptools/distribute for setup.py (optionally?) vs distutils

### ISSUE THREAD

**Issue by k0s** [photo/openphoto-python#4]
setuptools and distribute allow you to `python setup.py develop` as well as to install dependencies; i.e. we require oauth2 (https://github.com/openphoto/openphoto-python/blob/master/setup.py#L9) but it is not actually installed with python setup.py install.  I would recommend just requiring setuptools or distribute, but you can also optionally support them in the same setup.py; see https://github.com/pypa/virtualenv/blob/develop/setup.py for example.

I'm happy to do this if there is interest (or at least no dissent)

**Comment by k0s** [comment]
After python setup.py install I currently get:

(openphoto)│openphoto 
Traceback (most recent call last):
  File "/home/jhammel/mozilla/src/openphoto/bin/openphoto", line 13, in <module>
    from openphoto import OpenPhoto
  File "/home/jhammel/mozilla/src/openphoto/local/lib/python2.7/site-packages/openphoto/**init**.py", line 1, in <module>
    import oauth2 as oauth
ImportError: No module named oauth2

**Comment by walkah** [comment]
good call, thanks!
