### ISSUE TITLE
doesn't work with https

### ISSUE THREAD

**Issue by Notmarrco** [photo/openphoto-python#51]
in my config file I wrote the host without "https" and I get this error : 

```
Traceback (most recent call last):
  File "./import.py", line 23, in <module>
    resp = client.get("/photos/list.json")
  File "/usr/local/lib/python2.6/dist-packages/trovebox/http.py", line 92, in get
    return self._process_response(response)
  File "/usr/local/lib/python2.6/dist-packages/trovebox/http.py", line 188, in _process_response
    (response.status_code, response.reason))
trovebox.errors.Trovebox404Error: HTTP Error 404: Not Found
```

I can correct this by replacing "http" with "https" at line 69 in http.py : `url = urlunparse(('http', self.host, endpoint, '', '', ''))`
The problem is this urlunparse.

We probably need a scheme parsing in http.**init** to avoid the use of "http" hard written in `http.py`.

so we perhaps need a

**Comment by sneakypete81** [comment]
Quite right - https needs supporting. I'll take a look.

**Comment by sneakypete81** [comment]
This should be fixed now - please test with the latest development branch (https://github.com/photo/openphoto-python/archive/development.zip).
