### ISSUE TITLE
Properly handle Unicode characters in post params

### ISSUE THREAD

**Issue by jmathai** [photo/openphoto-python#7]
From: https://gist.github.com/1732810

```
Processing 906 of 3975 2768847584.json ...
Traceback (most recent call last):
  File "import.py", line 66, in <module>
    main()
  File "import.py", line 44, in main
    resp = client.post('/photo/upload.json', params)
  File "/Library/Python/2.7/site-packages/openphoto-0.1-py2.7.egg/openphoto/__init__.py", line 41, in post
    body = urllib.urlencode(params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1294, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 77: ordinal not in range(128)
```

**Comment by samatjain** [comment]
My research into this:

OpenPhoto's API sends certain things (photo metadata like titles, tags, etc in this case) as POST parameters. POST parameters are limited to ASCII (no Unicode), and anything outside of ASCII should be URL encoded. While you can get away without URL encoding, apparently Python is strict about it, hence the error.

The OpenPhoto client API needs to URL encode parameters, and likewise the OpenPhoto server needs to un-URL encode the parameters when received (check: does PHP does this automatically for POST parameters?)

**Comment by sirlatrom** [comment]
I worked around this by encoding the 'title' and 'tags' entries in the params dict.

``` python
            client = oauth.Client(consumer, token)
            params['title'] = params['title'].encode('utf-8')
            params['tags'] = params['tags'].encode('utf-8')
            body = urllib.urlencode(params)
```

**Comment by jmathai** [comment]
Thanks. Could you send this as a pull request?

**Comment by walkah** [comment]
So, I think we need to do more than just title & tags, no? I think to be safe we should ensure that everything in the params dict is utf-8 encoded. I think something like this?

``` python
import types

params = dict([(k,v.encode('utf-8') if type(v) is types.UnicodeType else v) \
for (k,v) in params.items()])
```

**Comment by sirlatrom** [comment]
Quite, and I can confirm the necessity of at least also encoding the 'description' field. Is there any way it could cause problems to encode any of the other entries?

**Comment by olberger** [comment]
I've applied https://github.com/openphoto/openphoto-python/issues/7#issuecomment-5165165 to import.py and it seems rather safe.

I guess it could be applied maybe. Anyone ?

**Comment by jmathai** [comment]
@olberger I think that's the right approach.

If you or @sirlatrom could send that as a pull request @walkah or I will merge it.
